const objectTypes = [
  { name: "G/L Accounts", key: 1 },
  { name: "Business Partner", key: 2 },
  { name: "Bank Codes", key: 3 },
  { name: "Items", key: 4 },
  { name: "Tax Definition", key: 5 },
  { name: "Price Lists", key: 6 },
  { name: "Special Prices", key: 7 },
  { name: "Item Properties", key: 8 },
  { name: "Rate Differences	", key: 9 },
  { name: "Card Groups	", key: 10 },
  { name: "Contact Persons", key: 11 },
  { name: "Users	", key: 12 },
  { name: "A/R Invoice	", key: 13 },
  { name: "A/R Credit Memo	", key: 14 },
  { name: "Delivery", key: 15 },
  { name: "Returns	", key: 16 },
  { name: "Sales Order		", key: 17 },
  { name: "A/P Invoice		", key: 18 },
  { name: "A/P Credit Memo", key: 19 },
  { name: "Goods Receipt PO", key: 20 },
  { name: "Goods Return		", key: 21 },
  { name: "Purchase Order		", key: 22 },
  { name: "Sales Quotation", key: 23 },
  { name: "Incoming Payment", key: 24 },
  { name: "Deposit	", key: 25 },
  { name: "Reconciliation History", key: 26 },
  { name: "Check Register	", key: 27 },
  { name: "Journal Voucher Entry	", key: 28 },
  { name: "Journal Vouchers List	", key: 29 },
  { name: "Journal Entry", key: 30 },
  { name: "Items - Warehouse	", key: 31 },
  { name: "Print Preferences", key: 32 },
  { name: "Activities", key: 33 },
  { name: "Recurring Postings	", key: 34 },
  { name: "Document Numbering	", key: 35 },
  { name: "Credit Cards	", key: 36 },
  { name: "Currency Codes	", key: 37 },
  { name: "CPI Codes	", key: 38 },
  { name: "Administration	", key: 39 },
  { name: "Payment Terms	", key: 40 },
  { name: "Preferences	", key: 41 },
  { name: "External Bank Statement Received	", key: 42 },
  { name: "Manufacturers	", key: 43 },
  { name: "Card Properties	", key: 44 },
  { name: "Journal Entry Codes	", key: 45 },
  { name: "Outgoing Payments	", key: 46 },
  { name: "Serial Numbers		", key: 47 },
  { name: "Loading Expenses	", key: 48 },
  { name: "Delivery Types	", key: 49 },
  { name: "Length Units		", key: 50 },
  { name: "Weight Units	", key: 51 },
  { name: "Item Groups		", key: 52 },
  { name: "Sales Employee	", key: 53 },
  { name: "Report – Selection Criteria	", key: 54 },
  { name: "Posting Templates	", key: 55 },
  { name: "Customs Groups	", key: 56 },
  { name: "Checks for Payment	", key: 57 },
  { name: "Whse Journal	", key: 58 },
  { name: "Goods Receipt	", key: 59 },
  { name: "Goods Issue	", key: 60 },
  { name: "Cost Center	", key: 61 },
  { name: "Cost Rate	", key: 62 },
  { name: "Project Codes	", key: 63 },
  { name: "Warehouses	", key: 64 },
  { name: "Commission Groups	", key: 65 },
  { name: "Product Tree	", key: 66 },
  { name: "Inventory Transfer		", key: 67 },
  { name: "Production Instructions	", key: 68 },
  { name: "Landed Costs	", key: 69 },
  { name: "Payment Methods	", key: 70 },
  { name: "Credit Card Payment	", key: 71 },
  { name: "Credit Card Management	", key: 72 },
  { name: "Customer/Vendor Cat. No.		", key: 73 },
  { name: "Credit Payments		", key: 74 },
  { name: "CPI and FC Rates	", key: 75 },
  { name: "Postdated Deposit	", key: 76 },
  { name: "Budget		", key: 77 },
  { name: "Budget Cost Assess. Mthd	", key: 78 },
  { name: "Retail Chains	", key: 79 },
  { name: "Alerts Template	", key: 80 },
  { name: "Alerts		", key: 81 },
  { name: "Received Alerts	", key: 82 },
  { name: "Message Sent	", key: 83 },
  { name: "Activity Subjects	", key: 84 },
  { name: "Special Prices for Groups", key: 85 },
  { name: "Application Start	", key: 86 },
  { name: "Distribution List	", key: 87 },
  { name: "Shipping Types	", key: 88 },
  { name: "Outgoing	", key: 89 },
  { name: "Transition	", key: 90 },
  { name: "Budget Scenario	", key: 91 },
  { name: "Interest Prices	", key: 92 },
  { name: "User Defaults	", key: 93 },
  { name: "Serial Numbers for Items	", key: 94 },
  { name: "Financial Report Templates	", key: 95 },
  { name: "Financial Report Categories	", key: 96 },
  { name: "Opportunity", key: 97 },
  { name: "Interest		", key: 98 },
  { name: "Interest Level	", key: 99 },
  { name: "Information Source	", key: 100 },
  { name: "Opportunity Stage	", key: 101 },
  { name: "Defect Cause", key: 102 },
  { name: "Activity Types	", key: 103 },
  { name: "Meetings Location	", key: 104 },
  { name: "Service Calls	", key: 105 },
  { name: "Batch No. for Item	", key: 106 },
  { name: "Alternative Items 2	", key: 107 },
  { name: "Partners	", key: 108 },
  { name: "Competitors	", key: 109 },
  { name: "User Validations	", key: 110 },
  { name: "Posting Period	", key: 111 },
  { name: "Drafts		", key: 112 },
  { name: "Batches and Serial Numbers	", key: 113 },
  { name: "User Display Cat.", key: 114 },
  { name: "Lender – Pelecard	", key: 115 },
  { name: "Withholding Tax Deduction Hierarchy	", key: 116 },
  { name: "Withholding Tax Deduction Groups	", key: 117 },
  { name: "Branches	", key: 118 },
  { name: "Departments	", key: 119 },
  { name: "Confirmation Level	", key: 120 },
  { name: "Approval Templates	", key: 121 },
  { name: "Docs. for Confirmation	", key: 122 },
  { name: "Checks for Payment Drafts	", key: 123 },
  { name: "Company Info	", key: 124 },
  { name: "Freight Setup		", key: 125 },
  { name: "Sales Tax Authorities	", key: 126 },
  { name: "Sales Tax Authorities Type	", key: 127 },
  { name: "Sales Tax Codes	", key: 128 },
  { name: "Countries	", key: 129 },
  { name: "States	", key: 130 },
  { name: "Address Formats	", key: 131 },
  { name: "A/R Correction Invoice	", key: 132 },
  { name: "Cash Discount	", key: 133 },
  { name: "Query Catagories	", key: 134 },
  { name: "Triangular Deal	", key: 135 },
  { name: "Data Migration	", key: 136 },
  { name: "Workstation ID	", key: 137 },
  { name: "Indicator	", key: 138 },
  { name: "Goods Shipment	", key: 139 },
  { name: "Payment Draft	", key: 140 },
  { name: "Query Wizard	", key: 141 },
  { name: "Account Segmentation	", key: 142 },
  { name: "Account Segmentation Categories	", key: 143 },
  { name: "Location	", key: 144 },
  { name: "1099 Forms	", key: 145 },
  { name: "Cycle	", key: 146 },
  { name: "Payment Methods for Payment Wizard	", key: 147 },
  { name: "1099 Opening Balance	", key: 148 },
  { name: "Dunning Interest Rate	", key: 149 },
  { name: "BP Priorities	", key: 150 },
  { name: "Dunning Letters	", key: 151 },
  { name: "User Fields - Description	", key: 152 },
  { name: "User Tables	", key: 153 },
  { name: "My Menu Items	", key: 154 },
  { name: "Payment Run	", key: 155 },
  { name: "Pick List	", key: 156 },
  { name: "Payment Wizard	", key: 157 },
  { name: "Payment Results Table	", key: 158 },
  { name: "Payment Block	", key: 159 },
  { name: "Queries	", key: 160 },
  { name: "Central Bank Ind.	", key: 161 },
  { name: "Inventory Revaluation	", key: 162 },
  { name: "A/P Correction Invoice	", key: 163 },
  { name: "A/P Correction Invoice Reversal	", key: 164 },
  { name: "A/R Correction Invoice	", key: 165 },
  { name: "A/R Correction Invoice Reversal	", key: 166 },
  { name: "Service Call Statuses	", key: 167 },
  { name: "Service Call Types	", key: 168 },
  { name: "Service Call Problem Types	", key: 169 },
  { name: "Contract Template	", key: 170 },
  { name: "Employees	", key: 171 },
  { name: "Employee Types	", key: 172 },
  { name: "Employee Status	", key: 173 },
  { name: "Termination Reason	", key: 174 },
  { name: "Education Types	", key: 175 },
  { name: "Customer Equipment Card	", key: 176 },
  { name: "Agent Name	", key: 177 },
  { name: "Withholding Tax	", key: 178 },
  { name: "Already Displayed 347, 349 and WTax Reports	", key: 179 },
  { name: "Tax Report	", key: 180 },
  { name: "Bill of Exchange for Payment	", key: 181 },
  { name: "Bill Of Exchang Transaction	", key: 182 },
  { name: "File Format	", key: 183 },
  { name: "Period Indicator	", key: 184 },
  { name: "Doubtful Debts	", key: 185 },
  { name: "Holiday Table	", key: 186 },
  { name: "BP - Bank Account	", key: 187 },
  { name: "Service Call Solution Statuses ", key: 188 },
  { name: "Service Call Solutions	", key: 189 },
  { name: "Service Contracts	", key: 190 },
  { name: "Service Calls	", key: 191 },
  { name: "Service Call Origins	", key: 192 },
  { name: "User Key Description	", key: 193 },
  { name: "Queue	", key: 194 },
  { name: "Inflation Wizard	", key: 195 },
  { name: "Dunning Terms	", key: 196 },
  { name: "Dunning Wizard	", key: 197 },
  { name: "Sales Forecast	", key: 198 },
  { name: "MRP Scenarios	", key: 199 },
  { name: "Territories	", key: 200 },
  { name: "Industries	", key: 201 },
  { name: "Production Order	", key: 202 },
  { name: "A/R Down Payment	", key: 203 },
  { name: "A/P Down Payment	", key: 204 },
  { name: "Package Types	", key: 205 },
  { name: "User-Defined Object	", key: 206 },
  { name: "Data Ownership - Objects	", key: 207 },
  { name: "Data Ownership - Exceptions	", key: 208 },
  { name: "", key: 209 },
  { name: "Employee Position	", key: 210 },
  { name: "Employee Teams	", key: 211 },
  { name: "Relationships	", key: 212 },
  { name: "Recommendation Data	", key: 213 },
  { name: "User Autorization Tree	", key: 214 },
  { name: "Predefined Text	", key: 215 },
  { name: "Box Definition		", key: 216 },
  { name: "Activity Status	", key: 217 },
  { name: "312	", key: 218 },
  { name: "User-Defined Values	", key: 219 },
  { name: "Periods Category	", key: 220 },
  { name: "Attachments	", key: 221 },
  { name: "Grid Filter", key: 222 },
  { name: "User Language Table	", key: 223 },
  { name: "Multi-Language Translation	", key: 224 },
  { name: "", key: 225 },
  { name: "", key: 226 },
  { name: "", key: 227 },
  { name: "Dynamic Interface (Strings)	", key: 229 },
  { name: "Saved Reconciliations	", key: 230 },
  { name: "House Bank Accounts	", key: 231 },
  { name: "Document	", key: 232 },
  { name: "Document Generation Parameter Sets	", key: 233 },
  { name: "#740	", key: 234 },
  { name: "Account Category	", key: 238 },
  { name: "Bank Charges Allocation Codes	", key: 239 },
  { name: "Cash Flow Transactions - Rows	", key: 241 },
  { name: "Cash Flow Line Item	", key: 242 },
  { name: "Business Place	", key: 247 },
  { name: "Local Era Calendar	", key: 250 },
  { name: "Cost Accounting Dimension	", key: 251 },
  { name: "Service Code Table	", key: 254 },
  { name: "Service Group for Brazil	", key: 255 },
  { name: "Material Group	", key: 256 },
  { name: "NCM Code	", key: 257 },
  { name: "CFOP for Nota Fiscal	", key: 258 },
  { name: "CST Code for Nota Fiscal	", key: 259 },
  { name: "Usage of Nota Fiscal	", key: 260 },
  { name: "Closing Date Procedure	", key: 261 },
  { name: "Nota Fiscal Numbering	", key: 263 },
  { name: "Nota Fiscal Tax Category (Brazil)	", key: 264 },
  { name: "Counties	", key: 265 },
  { name: "Tax Code Determination	", key: 266 },
  { name: "BoE Document Type	", key: 267 },
  { name: "BoE Portfolio	", key: 268 },
  { name: "BoE Instruction	", key: 269 },
  { name: "Tax Parameter	", key: 271 },
  { name: "Tax Type Combination	", key: 275 },
  { name: "Tax Formula Master Table	", key: 276 },
  { name: "CNAE Code	", key: 278 },
  { name: "Sales Tax Invoice	", key: 280 },
  { name: "Purchase Tax Invoice		", key: 281 },
  { name: "Cargo Customs Declaration Numbers	", key: 283 },
  { name: "Resources	", key: 290 },
  { name: "Resource Properties	", key: 291 },
  { name: "ResGrpCod	", key: 292 },
  { name: "RecordSet	", key: 300 },
  { name: "Bridge	", key: 305 },
  { name: "Internal Reconciliation	", key: 321 },
  { name: "POS Master Data	", key: 541 },
  { name: "Stock Transfer Draft		", key: 1179 },
  { name: "Messaging Service Settings	", key: 10000105 },
  { name: "Batch Numbers Master Data	", key: 10000044 },
  { name: "Serial Numbers Master Data	", key: 10000045 },
  { name: "IVL Vs OINM Keys	", key: 10000062 },
  { name: "Inventory Posting	", key: 10000071 },
  { name: "Financial Year Master	", key: 10000073 },
  { name: "Sections	", key: 10000074 },
  { name: "Certificate Series	", key: 10000075 },
  { name: "Nature of Assessee	", key: 10000077 },
  { name: "Document Type List	", key: 10000196 },
  { name: "UoM Group	", key: 10000197 },
  { name: "UoM Master Data	", key: 10000199 },
  { name: "Bin Field Configuration	", key: 10000203 },
  { name: "Bin Location Attribute	", key: 10000204 },
  { name: "Warehouse Sublevel	", key: 10000205 },
  { name: "Bin Location	", key: 10000206 },
  { name: "DNF Code	", key: 140000041 },
  { name: "Authorization Group	", key: 231000000 },
  { name: "E-Mail Group	", key: 234000004 },
  { name: "Government Payment Code	", key: 243000001 },
  { name: "Inventory Opening Balance		", key: 310000001 },
  { name: "Batch Attributes in Location	", key: 310000008 },
  { name: "Legal List Format	", key: 410000005 },
  { name: "Object: HR Employee Transfer		", key: 480000001 },
  { name: "Tax Code Determination	", key: 540000005 },
  { name: "Purchase Quotation		", key: 540000006 },
  { name: "Recurring Transaction Template	", key: 540000040 },
  { name: "Cost Center Type	", key: 540000042 },
  { name: "Accrual Type	", key: 540000048 },
  { name: "Nota Fiscal Model	", key: 540000056 },
  { name: "Brazil Fuel Indexer", key: 540000067 },
  { name: "Brazil Beverage Indexer	", key: 540000068 },
  { name: "Cockpit Main Table	", key: 1210000000 },
  { name: "Inventory Transfer Request	", key: 1250000001 },
  { name: "Blanket Agreement	", key: 1250000025 },
  { name: "Key Performance Indicator Package	", key: 1320000000 },
  { name: "Target Group	", key: 1320000002 },
  { name: "Campaign	", key: 1320000012 },
  { name: "Retorno Operation Codes	", key: 1320000028 },
  { name: "Product Source Code	", key: 1320000039 },
  { name: "Fixed Assets Depreciation Types		", key: 1470000000 },
  { name: "Fixed Assets Account Determination	", key: 1470000002 },
  { name: "Fixed Asset Depreciation Areas	", key: 1470000003 },
  { name: "Depreciation Type Pools	", key: 1470000004 },
  { name: "Asset Classes	", key: 1470000032 },
  { name: "Asset Groups	", key: 1470000046 },
  { name: "G/L Account Determination Criteria - Inventory	", key: 1470000048 },
  { name: "Capitalization	", key: 1470000049 },
  { name: "G/L Account Advanced Rules	", key: 1470000057 },
  { name: "Credit Memo	", key: 1470000060 },
  { name: "Bar Code Master Data	", key: 1470000062 },
  { name: "Inventory Counting	", key: 1470000065 },
  { name: "Discount Groups	", key: 1470000077 },
  { name: "Cycle Count Determination	", key: 1470000092 },
  { name: "Purchase Request	", key: 1470000113 },
  { name: "Workflow - Task Details	", key: 1620000000 },
  { name: "Purchase Blanked Agreement", key: 1250000025 },
];

export default function getDocumentNumberingByCode(code:any) {
  let data = objectTypes.filter((e) => e?.key == code);

  return data.length > 0 ? data[0]?.name : "";
}
